### ISSUE TITLE
why fork?

### ISSUE THREAD

**Issue by xen0n** [dfang/wechat-work-go#2]
今天跟同事聊天，他发现 Go 的企业微信 SDK 有很多竞品，我就看到这个。。。

我看你主要就加了一些类型、接口的支持，这是基于什么考虑而选择 fork 的呢？ 🤔

**Comment by dfang** [comment]
改动比较大 自己fork比较方便

**Comment by dfang** [comment]
打算规划一下 好好开发 欢迎加入

**Comment by xen0n** [comment]
任何改动都可以沟通，因为无预警 fork 尤其改掉 license 不是友善的行为。只是想知道一下初衷。

**Comment by xen0n** [comment]
例如你觉得公共 API 接口设计有问题，有什么问题？你觉得何种设计更恰当？这些问题如果有讨论，最后产出的成品对用户相信会更友好。

我看到了你的一些想法，我项目里也有人就功能缺失提问，这都鼓励我继续进行开发。所以希望能听一下你的想法。

**Comment by dfang** [comment]
@xen0n license 这点确实很对不起，创建库的时候默认选的， 但是我一开始就在README 里指明了从commit fork 的

**Comment by dfang** [comment]
另外 go的项目 因为引用路径的原因 自己建库 更方便 随便折腾， 我觉得你那个库 名字也不好听 :)

**Comment by xen0n** [comment]
> 我觉得你那个库 名字也不好听 :)

233 你的包名又长，`package xxx` 的部分又有大写字母，我也觉得不好听 🙃

另外关于“微信”译作“WeChat”还是“Weixin”这一点，我的判断很简单：企业微信 API 的文档位于 `work.weixin.qq.com` 域名，因此包名以 `workweixin` 为基础，再缩短一些，就是我的包名了。

**Comment by dfang** [comment]
你也按你的思路把获取和缓存access_token的逻辑优化一下啊

**Comment by xen0n** [comment]
access_token 逻辑问题在哪？我不知道你要优化什么。。

**Comment by dfang** [comment]
你觉得不需要那就算了吧

**Comment by xen0n** [comment]
这沟通。。我是真不知道，你的想法是什么？

**Comment by robert7git** [comment]
> 另外 go的项目 因为引用路径的原因 自己建库 更方便 随便折腾， 我觉得你那个库 名字也不好听 :)

对的，go的项目，如果作者不维护或者不接受pr 只能 自己干了。
确实这是 go 包管理器 不好。
